<a href="https://colab.research.google.com/github/atharva0300/Machine-Learning/blob/main/EMML/lec1_vectors_in_ml.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
v = np.array([1 , -1 , 2]);
w = np.array([2 , 5 , 2]);

In [10]:
print(v+w)    # addition

[3 4 4]


In [4]:
print(v-w)  # subtraction

[-1 -6  0]


In [6]:
print(3*v)  # scalar multiplication

[ 3 -3  6]


In [15]:
print(v*w)  # vector multiplication

[ 2 -5  4]


In [16]:
print(np.dot(v,w))

1


In [11]:
print(np.linalg.norm(v))  # length of v

2.449489742783178


In [13]:
print(np.linalg.norm(w))  # length of w

5.744562646538029


In [19]:
# angle between v and w
# dotProduct = v*w  -> this is not dot product
dotProduct = np.dot(v,w)
normV = np.linalg.norm(v)
normW = np.linalg.norm(w)
normMultiplication = normV * normW
cosineAngle = dotProduct / normMultiplication
thetaRadians = np.arccos(np.clip(cosineAngle , -1 , 1))
print(thetaRadians)

1.4996694643494421


In [20]:
thetaDegrees = np.degrees(thetaRadians)
print(thetaDegrees)

85.9247309718679
