<a href="https://colab.research.google.com/github/atharva0300/Machine-Learning/blob/main/EMML/lec2_basics_of_matrix_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
p = np.array([[1,7] , [2,1] , [3,2]]) # matrix
print(p)

[[1 7]
 [2 1]
 [3 2]]


In [3]:
q = np.array([[1,1] , [1,-1]])
print(q)

[[ 1  1]
 [ 1 -1]]


In [6]:
p.size  # number of elements in p

6

In [7]:
q.size  # number of elenets in q

4

In [10]:
c = np.add(p,q) # addition

ValueError: operands could not be broadcast together with shapes (3,2) (2,2) 

In [9]:
q2 = np.array([[1,1] , [1,-1] , [3,2]])
print(q2)

[[ 1  1]
 [ 1 -1]
 [ 3  2]]


In [11]:
c = np.add(p,q2)
print(c)

[[2 8]
 [3 0]
 [6 4]]


In [13]:
d = np.subtract(p,q2)
print(d)

[[0 6]
 [1 2]
 [0 0]]


In [14]:
e = np.multiply(p,q2)
print(e)

[[ 1  7]
 [ 2 -1]
 [ 9  4]]


In [15]:
r = np.array([[1,3,1] , [1,0,1]])
print(r)

[[1 3 1]
 [1 0 1]]


In [17]:
c2 = np.dot(p , r)
print(c2)

[[8 3 8]
 [3 6 3]
 [5 9 5]]


In [21]:
# determinant
det = np.linalg.det(c2)
print(det)
# answer is 0 -> singular matrix

0.0


In [22]:
q = np.array([[1,1] , [1,-1]])
print(q)

[[ 1  1]
 [ 1 -1]]


In [25]:
# inverse of a matrix

m = np.array([[1,-1] , [2,3]])
inverseM = np.linalg.inv(m)
print(inverseM)

[[ 0.6  0.2]
 [-0.4  0.2]]
